development:
  adapter: postgresql
  database: text_development
  pool: 5
  timeout: 5000
  encoding: unicode

test:
  adapter: postgresql
  database: text_test
  pool: 5
  timeout: 5000
  encoding: unicode

staging:
  adapter: postgresql
  database: text_staging
  pool: 5
  timeout: 5000
  encoding: unicode

production:
  adapter: postgresql
  database: text_production
  pool: 5
  timeout: 5000
  encoding: unicode
